FROM python:3.6.4

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

# set working directory
RUN mkdir /usr/src/catalog-api
WORKDIR /usr/src/catalog-api

# add requirements
ADD requirements.txt /usr/src/catalog-api/requirements.txt
RUN pip install -r requirements.txt

# Copy project files
ADD . /usr/src/catalog-api

# run server
CMD ["python3", "api.py"]
