version: "3.0"
services:
  webapp:
    hostname: webapp
    container_name: catalog_webapp
    build:
      context: ../catalog-app
      dockerfile: Dockerfile-nodejs
    depends_on:
      - flaskapi
    links:
      - flaskapi
    volumes:
      - "../catalog-app:/usr/src/catalog-app"
      - "/usr/src/catalog-app/node_modules"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${NODE_PORT}
    tty: true
  flaskapi:
    hostname: flaskapi
    container_name: catalog_api
    build:
      context: ../catalog-api
      dockerfile: Dockerfile-python
    depends_on:
      - postgresdb
    links:
      - postgresdb
    volumes:
      - "../catalog-api:/usr/src/catalog-api"
    ports:
      - "8000:8000"
    command: sh -c "./wait-for.sh postgresdb:5432 -- python3 api.py"
    tty: true
  postgresdb:
    hostname: postgresdb
    container_name: catalog_db
    build:
      context: ../catalog-db
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    tty: true
