FROM python:3.6.4

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

# set working directory
RUN mkdir /usr/src/catalog_api
WORKDIR /usr/src/catalog_api

# add requirements
ADD requirements.txt /usr/src/catalog_api/requirements.txt
RUN pip install -r requirements.txt

# Copy project files
ADD . /usr/src/catalog_api

# Set environment variables
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD n0t4g00dp4ssw0rd
ENV POSTGRES_HOST catalog_db
ENV POSTGRES_PORT 5432
ENV POSTGRES_DB catalog
ENV SECRET_KEY th1s1s4str0ngs3cr3tk3y
