FROM node:latest

RUN mkdir /usr/src/catalog-app
WORKDIR /usr/src/catalog-app

ADD package.json /usr/src/catalog-app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.0.15 -g --silent

# Copy project files
ADD . /usr/src/catalog-app

ENV PATH /usr/src/catalog-app/node_modules/.bin:$PATH

CMD ["npm", "run", "start"]
